# Generated by Django 4.1.7 on 2023-03-20 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('alternative_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.FloatField()),
                ('upper', models.FloatField()),
                ('measurment', models.CharField(choices=[('1', '%'), ('2', 'ppm')], max_length=5)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_elements_name', to='nutrient.element')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nutrients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrienties', to='nutrient.nutrient')),
                ('parent_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cropies', to='nutrient.crop')),
            ],
            managers=[
                ('chatbot_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
